[font]
size = 14.0

[font.bold]
family = "DepartureMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "DepartureMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "DepartureMono Nerd Font"
style = "Italic"

[font.normal]
family = "DepartureMono Nerd Font"
style = "Regular"

[window]
decorations = "full"
