"$schema" = "https://starship.rs/config-schema.json"

# format = "$character$all"
format = "$character$directory"

add_newline = false

[character]
success_symbol = "[](bold green)"
# success_symbol = "[󰁕](bold green)"
# success_symbol = "[❯](bold green)"
# success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[package]
disabled = true
