[language-server.rust-analyzer]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]
config = { "checkOnSave" = { "command" = "clippy" } }

[language-server.gdscript]
command = "nc"
args = ["localhost", "6005"]

[[language]]
name = "gdscript"
roots = ["project.godot"]
language-servers = ["gdscript"]

[[language]]
name = "rust"
auto-format = false
language-servers = ["rust-analyzer"]
