# Author : blazkowolf

[palette]
fg = "#e4e4e4"
"fg+1" = "#f4f4ff"
"fg+2" = "#f5f5f5"
white = "#ffffff"
black = "#000000"
bg-1 = "#101010"
bg = "#181818"
"bg+1" = "#282828"
"bg+2" = "#453d41"
"bg+3" = "#484848"
"bg+4" = "#52494e"
red-1 = "#c73c3f"
red = "#f43841"
"red+1" = "#ff4f58"
green = "#73d936"
yellow = "#ffdd33"
brown = "#cc8c3c"
quartz = "#95a99f"
niagara-2 = "#303540"
niagara-1 = "#565f73"
niagara = "#96a6c8"
wisteria = "#9e95c7"
